import Link from "next/link";
import Image from "next/image";
import { requestPasswordReset } from "@/lib/auth/actions";

interface PageProps { searchParams: Promise<{ error?: string; success?: string }> }

export default async function ForgotPasswordPage({ searchParams }: PageProps) {
  const params = await searchParams;
  return <main className="flex min-h-screen items-center justify-center bg-[#147fbd] px-5 py-10"><section className="w-full max-w-md rounded-2xl bg-white p-8 shadow-[0_16px_50px_rgba(7,53,82,0.25)]"><Image src="/logo.svg" alt="Logo Yayasan Al-Fityah" width={72} height={72} className="mb-5 h-16 w-16 object-contain" /><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#147fbd]">Yayasan Al-Fityah</p><h1 className="mt-3 text-2xl font-bold text-[#112b45]">Lupa password?</h1><p className="mt-2 text-sm leading-6 text-slate-500">Masukkan email akun. Kami akan mengirim link untuk membuat password baru.</p>{params.error && <p role="alert" className="mt-5 rounded-lg bg-[#fff1f2] p-3 text-sm font-medium text-[#c91d2e]">{params.error}</p>}{params.success && <p className="mt-5 rounded-lg bg-[#effaf5] p-3 text-sm font-medium text-[#087443]">{params.success}</p>}<form action={requestPasswordReset} className="mt-6 space-y-4"><label className="block text-sm font-semibold text-[#112b45]">Email<input name="email" type="email" required className="mt-2 w-full rounded-lg border border-[#c8d7e3] px-3 py-2.5 text-[#101820] outline-none focus:border-[#e52335]" placeholder="nama@yayasan.id" /></label><button className="w-full rounded-lg bg-[#e52335] px-4 py-3 text-sm font-bold text-white hover:bg-[#c91d2e]">Kirim link reset</button></form><Link href="/login" className="mt-5 block text-center text-sm font-semibold text-[#147fbd]">&larr; Kembali ke login</Link></section></main>;
}